services:
  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - backend




